[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --omit=dev --legacy-peer-deps"]

[phases.build]
cmds = ["npm install --legacy-peer-deps", "npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
